name: Update Version on PR Approval - IH

on:
  pull_request:
    branches:
      - dev

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for Specific Labels
      id: check_labels
      run: |
        labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" | jq -r '.[].name')
        if echo "$labels" | grep -qE "(Major|Minor|Build|Revision)"; then
          echo "has_specific_label=true" >> $GITHUB_ENV
          echo "label_name=$labels" >> $GITHUB_ENV
        else
          echo "has_specific_label=false" >> $GITHUB_ENV
        fi

    - name: Get PR Approver
      id: get_pr_approver
      if: needs.check_labels.outputs.has_specific_label == 'true'
      run: |
        approver=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
        echo "approver=$approver" >> $GITHUB_ENV

    - name: Increment Version and Commit Changes
      if: env.has_specific_label == 'true'
      run: |
        version=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' VersionamentoDinamicoGIT.csproj)
        version_parts=($(echo "$version" | tr '.' ' '))
        
        case "${{ env.label_name }}" in
          "Major")
            major=$((version_parts[0]+1))
            version="$major.0.0.0"
            ;;
          "Minor")
            minor=$((version_parts[1]+1))
            version="${version_parts[0]}.$minor.0.0"
            ;;
          "Build")
            build=$((version_parts[2]+1))
            version="${version_parts[0]}.${version_parts[1]}.$build.0"
            ;;
          "Revision")
            revision=$((version_parts[3]+1))
            version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.$revision"
            ;;
        esac
        
        echo "Atualizando a versão do App para $version no VersionamentoDinamicoGIT.csproj"
        sed -i "s/<Version>.*<\/Version>/<Version>$version<\/Version>/" VersionamentoDinamicoGIT.csproj
        
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --local user.name "$GITHUB_ACTOR"

        # Mudar para o branch 'dev' (assumindo que já existe)
        git checkout -b dev

        # Definir a configuração 'pull.rebase' para 'false' para realizar um merge
        git config pull.rebase false

        # Atualizar o branch 'dev' local com as alterações do repositório remoto
        git pull origin dev --allow-unrelated-histories

        # Adicionar as alterações e fazer o commit
        git add VersionamentoDinamicoGIT.csproj
        git commit -m "Action: Update version in VersionamentoDinamicoGIT.csproj" VersionamentoDinamicoGIT.csproj

        # Fazer o push para o repositório remoto no branch 'dev'
        git push origin dev